const gameModes = ["landmark", "nickname", "capital", "state"];

export type GameMode = "state" | "nickname" | "capital" | "landmark";

type StateInfo = {
  [key: string]: {
    state: string;
    nickname: string;
    capital: string;
    landmark: string;
  };
};

const stateInfo: StateInfo = {
  Alabama: {
    state: "Alabama",
    nickname: "The Yellowhammer State",
    capital: "Montgomery",
    landmark: "USS Alabama Battleship",
  },
  Alaska: {
    state: "Alaska",
    nickname: "The Last Frontier",
    capital: "Juneau",
    landmark: "Denali (Mount McKinley)",
  },
  Arizona: {
    state: "Arizona",
    nickname: "The Grand Canyon State",
    capital: "Phoenix",
    landmark: "Grand Canyon",
  },
  Arkansas: {
    state: "Arkansas",
    nickname: "The Natural State",
    capital: "Little Rock",
    landmark: "Crater of Diamonds State Park",
  },
  California: {
    state: "California",
    nickname: "The Golden State",
    capital: "Sacramento",
    landmark: "Golden Gate Bridge",
  },
  Colorado: {
    state: "Colorado",
    nickname: "The Centennial State",
    capital: "Denver",
    landmark: "Rocky Mountain National Park",
  },
  Connecticut: {
    state: "Connecticut",
    nickname: "The Constitution State",
    capital: "Hartford",
    landmark: "Mystic Seaport",
  },
  Delaware: {
    state: "Delaware",
    nickname: "The First State",
    capital: "Dover",
    landmark: "Rehoboth Beach",
  },
  Florida: {
    state: "Florida",
    nickname: "The Sunshine State",
    capital: "Tallahassee",
    landmark: "Walt Disney World",
  },
  Georgia: {
    state: "Georgia",
    nickname: "The Peach State",
    capital: "Atlanta",
    landmark: "Stone Mountain",
  },
  Hawaii: {
    state: "Hawaii",
    nickname: "The Aloha State",
    capital: "Honolulu",
    landmark: "Hawaiʻi Volcanoes National Park",
  },
  Idaho: {
    state: "Idaho",
    nickname: "The Gem State",
    capital: "Boise",
    landmark: "Shoshone Falls",
  },
  Illinois: {
    state: "Illinois",
    nickname: "The Prairie State",
    capital: "Springfield",
    landmark: "Willis Tower (Sears Tower)",
  },
  Indiana: {
    state: "Indiana",
    nickname: "The Hoosier State",
    capital: "Indianapolis",
    landmark: "Indianapolis Motor Speedway",
  },
  Iowa: {
    state: "Iowa",
    nickname: "The Hawkeye State",
    capital: "Des Moines",
    landmark: "National Mississippi River Museum & Aquarium",
  },
  Kansas: {
    state: "Kansas",
    nickname: "The Sunflower State",
    capital: "Topeka",
    landmark: "Monument Rocks",
  },
  Kentucky: {
    state: "Kentucky",
    nickname: "The Bluegrass State",
    capital: "Frankfort",
    landmark: "Mammoth Cave National Park",
  },
  Louisiana: {
    state: "Louisiana",
    nickname: "The Pelican State",
    capital: "Baton Rouge",
    landmark: "French Quarter",
  },
  Maine: {
    state: "Maine",
    nickname: "The Pine Tree State",
    capital: "Augusta",
    landmark: "Acadia National Park",
  },
  Maryland: {
    state: "Maryland",
    nickname: "The Old Line State",
    capital: "Annapolis",
    landmark: "Fort McHenry",
  },
  Massachusetts: {
    state: "Massachusetts",
    nickname: "The Bay State",
    capital: "Boston",
    landmark: "Faneuil Hall",
  },
  Michigan: {
    state: "Michigan",
    nickname: "The Great Lakes State",
    capital: "Lansing",
    landmark: "Mackinac Bridge",
  },
  Minnesota: {
    state: "Minnesota",
    nickname: "The North Star State",
    capital: "Saint Paul",
    landmark: "Mall of America",
  },
  Mississippi: {
    state: "Mississippi",
    nickname: "The Magnolia State",
    capital: "Jackson",
    landmark: "Vicksburg National Military Park",
  },
  Missouri: {
    state: "Missouri",
    nickname: "The Show Me State",
    capital: "Jefferson City",
    landmark: "Gateway Arch",
  },
  Montana: {
    state: "Montana",
    nickname: "The Treasure State",
    capital: "Helena",
    landmark: "Glacier National Park",
  },
  Nebraska: {
    state: "Nebraska",
    nickname: "The Cornhusker State",
    capital: "Lincoln",
    landmark: "Chimney Rock",
  },
  Nevada: {
    state: "Nevada",
    nickname: "The Silver State",
    capital: "Carson City",
    landmark: "Las Vegas Strip",
  },
  NewHampshire: {
    state: "New Hampshire",
    nickname: "The Granite State",
    capital: "Concord",
    landmark: "Mount Washington",
  },
  NewJersey: {
    state: "New Jersey",
    nickname: "The Garden State",
    capital: "Trenton",
    landmark: "Atlantic City Boardwalk",
  },
  NewMexico: {
    state: "New Mexico",
    nickname: "The Land of Enchantment",
    capital: "Santa Fe",
    landmark: "White Sands National Park",
  },
  NewYork: {
    state: "New York",
    nickname: "The Empire State",
    capital: "Albany",
    landmark: "Statue of Liberty",
  },
  NorthCarolina: {
    state: "North Carolina",
    nickname: "The Tar Heel State",
    capital: "Raleigh",
    landmark: "Biltmore Estate",
  },
  NorthDakota: {
    state: "North Dakota",
    nickname: "The Peace Garden State",
    capital: "Bismarck",
    landmark: "Theodore Roosevelt National Park",
  },
  Ohio: {
    state: "Ohio",
    nickname: "The Buckeye State",
    capital: "Columbus",
    landmark: "Cedar Point",
  },
  Oklahoma: {
    state: "Oklahoma",
    nickname: "The Sooner State",
    capital: "Oklahoma City",
    landmark: "National Cowboy & Western Heritage Museum",
  },
  Oregon: {
    state: "Oregon",
    nickname: "The Beaver State",
    capital: "Salem",
    landmark: "Crater Lake National Park",
  },
  Pennsylvania: {
    state: "Pennsylvania",
    nickname: "The Keystone State",
    capital: "Harrisburg",
    landmark: "Independence Hall",
  },
  RhodeIsland: {
    state: "Rhode Island",
    nickname: "The Ocean State",
    capital: "Providence",
    landmark: "The Breakers",
  },
  SouthCarolina: {
    state: "South Carolina",
    nickname: "The Palmetto State",
    capital: "Columbia",
    landmark: "Fort Sumter National Monument",
  },
  SouthDakota: {
    state: "South Dakota",
    nickname: "Mount Rushmore State",
    capital: "Pierre",
    landmark: "Mount Rushmore",
  },
  Tennessee: {
    state: "Tennessee",
    nickname: "The Volunteer State",
    capital: "Nashville",
    landmark: "Great Smoky Mountains National Park",
  },
  Texas: {
    state: "Texas",
    nickname: "The Lone Star State",
    capital: "Austin",
    landmark: "The Alamo",
  },
  Utah: {
    state: "Utah",
    nickname: "The Beehive State",
    capital: "Salt Lake City",
    landmark: "Zion National Park",
  },
  Vermont: {
    state: "Vermont",
    nickname: "The Green Mountain State",
    capital: "Montpelier",
    landmark: "Ben & Jerry's Factory",
  },
  Virginia: {
    state: "Virginia",
    nickname: "The Old Dominion State",
    capital: "Richmond",
    landmark: "Mount Vernon",
  },
  Washington: {
    state: "Washington",
    nickname: "The Evergreen State",
    capital: "Olympia",
    landmark: "Space Needle",
  },
  WestVirginia: {
    state: "West Virginia",
    nickname: "The Mountain State",
    capital: "Charleston",
    landmark: "New River Gorge Bridge",
  },
  Wisconsin: {
    state: "Wisconsin",
    nickname: "The Badger State",
    capital: "Madison",
    landmark: "Wisconsin Dells",
  },
  Wyoming: {
    state: "Wyoming",
    nickname: "The Equality State",
    capital: "Cheyenne",
    landmark: "Yellowstone National Park",
  },
} as const;

const initialStates = [
  "Alabama",
  "Alaska",
  "Arizona",
  "Arkansas",
  "California",
  "Colorado",
  "Connecticut",
  "Delaware",
  "Florida",
  "Georgia",
  "Hawaii",
  "Idaho",
  "Illinois",
  "Indiana",
  "Iowa",
  "Kansas",
  "Kentucky",
  "Louisiana",
  "Maine",
  "Maryland",
  "Massachusetts",
  "Michigan",
  "Minnesota",
  "Mississippi",
  "Missouri",
  "Montana",
  "Nebraska",
  "Nevada",
  "New Hampshire",
  "New Jersey",
  "New Mexico",
  "New York",
  "North Carolina",
  "North Dakota",
  "Ohio",
  "Oklahoma",
  "Oregon",
  "Pennsylvania",
  "Rhode Island",
  "South Carolina",
  "South Dakota",
  "Tennessee",
  "Texas",
  "Utah",
  "Vermont",
  "Virginia",
  "Washington",
  "West Virginia",
  "Wisconsin",
  "Wyoming",
];

const initialHighscores = [
  { name: "Jobe Giden", score: -13 },
  { name: "Jobe Giden", score: -69 },
  { name: "Jobe Giden", score: -1337 },
  { name: "Jobe Giden", score: -8008 },
  { name: "Jobe Giden", score: -58008 },
];

export { initialHighscores, stateInfo, initialStates, gameModes };
